'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AADE_Legal_Entities_Information.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;env:Envelope xmlns:env=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:ns1=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd&quot; xmlns:ns2=&quot;http://rgwspublic2/RgWsPublic2Service&quot; xmlns:ns3=&quot;http://rgwspublic2/RgWsPublic2&quot;&gt;
        '''   &lt;env:Header&gt;
        '''      &lt;ns1:Security&gt;
        '''         &lt;ns1:UsernameToken&gt;
        '''            &lt;ns1:Username&gt;&lt;!--{USERNAME}--&gt;&lt;/ns1:Username&gt;
        '''            &lt;ns1:Password&gt;&lt;!--{PASSWORD}--&gt;&lt;/ns1:Password&gt;
        '''         &lt;/ns1:UsernameToken&gt;
        '''      &lt;/ns1:Security&gt;
        '''   &lt;/env:Heade [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property request_afm() As String
            Get
                Return ResourceManager.GetString("request_afm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://www.w3.org/2003/05/soap-envelope&quot; xmlns:rgw=&quot;http://rgwspublic2/RgWsPublic2Service&quot;&gt;
        '''   &lt;soap:Header/&gt;
        '''   &lt;soap:Body&gt;
        '''      &lt;rgw:rgWsPublic2VersionInfo/&gt;
        '''   &lt;/soap:Body&gt;
        '''&lt;/soap:Envelope&gt;.
        '''</summary>
        Friend ReadOnly Property request_version() As String
            Get
                Return ResourceManager.GetString("request_version", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
